"""
risk/covariance.py — Covariance estimators and matrix utilities.

Extracted from portfolio-risk-quant/utils.py and module_2_factor_models.py.

PUBLIC INTERFACE
────────────────
    is_psd(Sigma)              → bool
    nearest_psd(Sigma)         → np.ndarray
    condition_number(Sigma)    → float
    sample_cov(returns)        → np.ndarray
    ledoit_wolf(returns)       → np.ndarray
    factor_cov(returns, factors) → np.ndarray
    pca_cov(returns, n_components) → np.ndarray
"""

import numpy as np


# ── Matrix utilities ───────────────────────────────────────────────────────────

def is_psd(Sigma: np.ndarray, tol: float = 1e-8) -> bool:
    """True if matrix is positive semi-definite (all eigenvalues >= -tol)."""
    return bool(np.all(np.linalg.eigvalsh(Sigma) >= -tol))


def nearest_psd(Sigma: np.ndarray) -> np.ndarray:
    """Project to nearest PSD matrix by clipping negative eigenvalues to 0."""
    eigvals, eigvecs = np.linalg.eigh(Sigma)
    eigvals = np.maximum(eigvals, 0.0)
    return eigvecs @ np.diag(eigvals) @ eigvecs.T


def condition_number(Sigma: np.ndarray) -> float:
    """κ(Σ) = λ_max / λ_min. Lower is better-conditioned."""
    eigvals = np.linalg.eigvalsh(Sigma)
    return float(eigvals.max() / max(eigvals.min(), 1e-15))


# ── Covariance estimators ──────────────────────────────────────────────────────

def _to_array(returns) -> np.ndarray:
    return returns.values if hasattr(returns, "values") else np.asarray(returns)


def sample_cov(returns, annualize: bool = True) -> np.ndarray:
    """Sample covariance matrix. Conforms to CovEstimator protocol."""
    R = _to_array(returns)
    scale = 252 if annualize else 1
    return np.cov(R.T) * scale


def ledoit_wolf(returns, annualize: bool = True) -> np.ndarray:
    """
    Ledoit-Wolf analytical shrinkage estimator (sklearn).

    Shrinks toward a scaled identity target to reduce condition number.
    Conforms to CovEstimator protocol.
    """
    from sklearn.covariance import LedoitWolf as _LW
    R = _to_array(returns)
    scale = 252 if annualize else 1
    lw = _LW()
    lw.fit(R)
    return lw.covariance_ * scale


def factor_cov(returns, factors, annualize: bool = True) -> np.ndarray:
    """
    Factor-model covariance: Σ = B F_cov B^T + D.

    Factored structure reduces condition number relative to sample Σ.

    Parameters
    ----------
    returns : (T, N) asset returns
    factors : (T, k) factor returns (e.g. Fama-French Mkt-RF, SMB, HML)
    """
    R = _to_array(returns)
    F = _to_array(factors)
    T, k = F.shape
    scale = 252 if annualize else 1

    ones_col = np.ones((T, 1))
    X = np.hstack([ones_col, F])                       # (T, k+1) with intercept
    XtX_inv = np.linalg.inv(X.T @ X)
    coefs = XtX_inv @ X.T @ R                          # (k+1, N)

    B = coefs[1:].T                                    # (N, k) factor loadings
    residuals = R - X @ coefs                          # (T, N) idiosyncratic
    D_diag = np.var(residuals, axis=0, ddof=k + 1) * scale
    F_cov_mat = np.cov(F.T) * scale                    # (k, k)

    return B @ F_cov_mat @ B.T + np.diag(D_diag)


def marchenko_pastur_threshold(N: int, T: int, sigma2: float = 1.0) -> float:
    """
    Marchenko-Pastur upper bulk edge: λ₊ = σ²(1 + √(N/T))².

    Eigenvalues of a sample covariance above this threshold carry signal;
    eigenvalues below it are statistically indistinguishable from noise
    generated by a random matrix with N assets and T observations.

    Parameters
    ----------
    N      : number of assets
    T      : number of observations
    sigma2 : variance scale (use mean diagonal of daily sample cov)
    """
    q = N / T
    return float(sigma2 * (1.0 + np.sqrt(q)) ** 2)


def pca_cov(returns, n_components: int, annualize: bool = True) -> np.ndarray:
    """
    PCA-denoised covariance: keep top k eigenvectors, discard noise bulk.

    Marchenko-Pastur theory guides the choice of n_components: eigenvalues
    below λ+ = σ²(1 + √(N/T))² are statistically indistinguishable from noise.
    """
    R = _to_array(returns)
    scale = 252 if annualize else 1
    S = np.cov(R.T)

    eigvals, eigvecs = np.linalg.eigh(S)
    idx = np.argsort(eigvals)[::-1]
    eigvals, eigvecs = eigvals[idx], eigvecs[:, idx]

    eigvals_trunc = eigvals.copy()
    eigvals_trunc[n_components:] = 0.0

    return (eigvecs @ np.diag(eigvals_trunc) @ eigvecs.T) * scale
